AllCops:
  TargetRubyVersion: 2.5
ClassLength:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
BlockLength:
  Enabled: false
Metrics/AbcSize:
  Max: 30
Style/Documentation:
  Enabled: no
  