sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1
before_install: gem install bundler -v 1.16.3
deploy:
  provider: rubygems
  api_key:
    secure: Pbe2FUaQIe+pxgVOt6x9I5qA5BZNZHARdHlJpLEPpCjCUtsGQyOiPsjH6LeOACrR3jJhKqoqXacFkC6DfS1zLX8xhqBPoVfZNhuLOnST3hdru1sC3fauCtCym5/WxrGwn7qZvg6x39lUI0LhVp+3wOVw9ZoniYZwW8/mx93FZ8dUaNg567sYcYmFeLyeQKOKWInY8WiEPDU/jEgLMR4oEiwEhTwAgw6jpKwRPvkQfe8OsYASHjxQYRkAByE6Tzoy3PpBHz9tBEEUH1bCy1EWDExMcGXtl421WJw8+s2HjR/RJSHIaVschVD2OsI4xL/mqeSqLJuQdge2DH7p+Y9a7JB0ZYyBscPQW68gEVs5mkQJH9k9gJ3zHJ+DQ+o7rKBmdy+g9LOxcaPFAt1d+Hel4YSfQb2J29n4ydrigYoDz2Cpid3mzEEA8WbfpLGB8rjnw7FnemqoxGEQcSqg7rwAy3i47e3aa+LY5RbFjmCKdvAcbyhiGsbPGeePfqzAWkusP77jRA6P/evqpfLh1nMb284nw5gvWBc/EMvZfkZv3P53DK7Yo6zdrj7a6CBU9VRGN2VbyOdUpFDdS5kxO0xv+O+BgbBj31KAfHXQBgV2Qj983fYiYdjiuum30p1P9thyeYsF0/9mknGHs2sGIkl21hCceA3JasUmyo/I0eZsg/A=
  gem: gem_check_updates
  on:
    branch: master
    tags: true
    repo: mukopikmin/gem_check_updates
