sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.3
script: bundle exec rubocop --fail-level=W
deploy:
  provider: rubygems
  api_key:
    secure: Pbe2FUaQIe+pxgVOt6x9I5qA5BZNZHARdHlJpLEPpCjCUtsGQyOiPsjH6LeOACrR3jJhKqoqXacFkC6DfS1zLX8xhqBPoVfZNhuLOnST3hdru1sC3fauCtCym5/WxrGwn7qZvg6x39lUI0LhVp+3wOVw9ZoniYZwW8/mx93FZ8dUaNg567sYcYmFeLyeQKOKWInY8WiEPDU/jEgLMR4oEiwEhTwAgw6jpKwRPvkQfe8OsYASHjxQYRkAByE6Tzoy3PpBHz9tBEEUH1bCy1EWDExMcGXtl421WJw8+s2HjR/RJSHIaVschVD2OsI4xL/mqeSqLJuQdge2DH7p+Y9a7JB0ZYyBscPQW68gEVs5mkQJH9k9gJ3zHJ+DQ+o7rKBmdy+g9LOxcaPFAt1d+Hel4YSfQb2J29n4ydrigYoDz2Cpid3mzEEA8WbfpLGB8rjnw7FnemqoxGEQcSqg7rwAy3i47e3aa+LY5RbFjmCKdvAcbyhiGsbPGeePfqzAWkusP77jRA6P/evqpfLh1nMb284nw5gvWBc/EMvZfkZv3P53DK7Yo6zdrj7a6CBU9VRGN2VbyOdUpFDdS5kxO0xv+O+BgbBj31KAfHXQBgV2Qj983fYiYdjiuum30p1P9thyeYsF0/9mknGHs2sGIkl21hCceA3JasUmyo/I0eZsg/A=
  gem: gem_check_updates
  on:
    branch: master
    tags: true
    repo: mukopikmin/gem_check_updates
addons:
  code_climate:
    repo_token: bd103456b9581249a1b35fcee59e86b542bdd3babdd6e85181a1faefcd01d23f
notifications:
  email: false
  slack:
    secure: cWL+X3N1obm/mk3PsuH2JdahiVUEFuqn/k+FvWCK1awpWIJj9YFpJjDBN5BWr62SW3X0EMzxA7xvl8SLvaF9VgcCfMTxGCHK+nKXUvH6Hzs0g/HzJM1vDouRNpOGPIz3i4y4caGnmR1S/R5E6ed5w3htIf1mBCf1KaLpV2l3Dfjcov9iGEu5BFWgu8L0Y2kcxFrZZNmNR6ZDffrN3odY3etZzHgxJok9Z4wV8sivcgvncClfSSSKMTBL594h5QMC8ozwv+Aw5z5wG2OloKSw2FFrJshjkgQAxcf+b4I9YuMFQnzLNje0wHp/4YOtNvECmeEa3eemQaEo6aMTSpmsvrmm6BKjJhPQcPo0AQWMpQBQqezXRzF7j3aEwiAq1S3xnqm7a4iydwBk7Qn6VaqCsGgDrh/4qs+Q0slMPVxeTpUB4vZnJ1Gjk8QTHqguPY8K5PjKhsik2+Om5byc9/GqGp2N/s0nym8jBfCFWUVuti9j2ACq+uqMyqPxbsTqnVPYyU7kTFiTCi1VfM99fwkOiMRN4wD/KbtGB7ZmcU+svmgT7gtES8QZlTg5MnSyo1Z2sK1UJdzP8F6JKSAIosqZuw+lY5hsS/eY+pVkdwGKLNI3tE4Zrg9rNFPmfVS0iCVtHkydVckYphWtZ+XkYY6JLQWzXTPdRlIcvWlESyNySAQ=
after_success:
  - bundle exec codeclimate-test-reporter
